id: dockerfile-hidden-disclosure
brief:
    title: Dockerfile - Detect
    by: dhiyaneshDk
    level: medium
    about: Dockerfile was detected.
    label:
        - exposure
        - config
        - vuln
    score: CVSS:5.3
moves:
    - verb: GET
      to:
        - '{{BaseURL}}/.dockerfile'
        - '{{BaseURL}}/.Dockerfile'
        - '{{BaseURL}}/Dockerfile'
      signs:
        - "on": status
          status:
            - 200
        - "on": word
          has:
            - text/html
          in: header
          need: all
