id: phpstan-config
brief:
    title: PHPStan Configuration Page - Detect
    by: DhiyaneshDK
    level: info
    about: PHPStan configuration page was detected.
    label:
        - devops
        - exposure
        - vuln
moves:
    - verb: GET
      to:
        - '{{BaseURL}}/phpstan.neon'
      signs:
        - "on": word
          has:
            - 'parameters:'
          in: body
          need: all
        - "on": word
          has:
            - text/html
            - application/javascript
          in: header
          need: all
        - "on": status
          status:
            - 200
