id: kube-api-pods
brief:
    title: Kube API Pods
    by: sharath
    level: info
    about: Scans for kube pods
    label:
        - tech
        - k8s
        - kubernetes
        - devops
        - kube
        - discovery
moves:
    - verb: GET
      to:
        - '{{BaseURL}}/api/v1/namespaces/default/pods'
      signs:
        - "on": status
          status:
            - 200
        - "on": word
          has:
            - '"PodList":'
            - '"items":'
          in: body
          need: all
