id: grafana-default-login
brief:
    title: Grafana Default Login
    by: pdteam
    level: high
    about: Grafana default admin login credentials were detected.
    label:
        - grafana
        - default-login
        - vuln
    score: CVSS:8.3
moves:
    - verb: POST
      to:
        - '{{BaseURL}}/login'
      head:
        Accept: application/json, text/plain, */*
        Accept-Language: en-US,en;q=0.5
        Referer: '{{BaseURL}}'
        content-type: application/json
      body: '{"user":"{{username}}","password":"{{password}}"}'
      signs:
        - "on": word
          has:
            - grafana_session
          in: header
          need: all
        - "on": word
          has:
            - Logged in
          in: body
          need: all
        - "on": status
          status:
            - 200
